### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by matsuyani556**
fixes https://github.com/gree/patapata/issues/26

# Summary
Since patapata_core is currently using version 6 of package_info_plus, this was specified to be a version greater than 6.

### CODE REVIEW

**Review by Moncader — APPROVED** [review]

**Comment by matsuyani556** [comment]
The device_info_plus dependency used by Patapata’s DeviceInfoPlugin also needed to be updated.
However, updating to version 11 or higher caused flutter test to fail. Fixes for these test failures are also necessary.

**Comment by matsuyani556** [comment]
Updating device_info_plus also updates its dependent web package, which in turn causes dependency conflicts with Firebase-related packages. To resolve this, Firebase-related packages also need to be updated.

**Review by Moncader — APPROVED** [review]

**Review by toshiaki-satsuma — APPROVED** [review]

**Comment by matsuyani556** [comment]
Test case failed due to device_info_plus being updated to 11.2.0 ......

**Comment by matsuyani556** [comment]
From version 11.2.0, the device_info_plus package added modelName and isiOSAppOnMac for iOS and macOS devices.
(See changelog: [device_info_plus 11.2.0](https://pub.dev/packages/device_info_plus/changelog))

In patapata_core, the MethodChannel for device_info_plus is mocked during testing. Due to these additions, insufficient mock data caused test errors.

This issue will be addressed by adding the missing data to the mock responses. However, similar issues might arise in the future as the package evolves.

It is worth noting that this issue only occurs during testing and does not impact actual usage.

**Review by toshiaki-satsuma — APPROVED** [review]

**Review by Moncader — APPROVED** [review]

**Pull request merged**
